# a stochastic model of a spillover event and subsequent outbreak in a focal host population.
# 1. random waiting time for a single spillover event (pathogen introduction) 
# 2. random number of secondary infections generated by first infected host,
# 3. random number of infected hosts in the subsequent transmission chain, discrete time



# 1: waiting time for spillover

spill.rate <- 2  # average number of spillovers per unit time
num.draws <- 100   # trials

# randomly draw
wait.time <- rexp(n=num.draws,rate=spill.rate)

# few draws
if(num.draws <= 10){ # one or few draws: print all wait times individually
  print(paste("waiting time(s): ",round(wait.time,digits=3),sep=""))
}
if(num.draws >1) {   # multiple draws: print mean and plot histogram
  print(paste("mean waiting time = ",round(mean(wait.time),digits=3),sep = ""))
  hist(wait.time)
}


#2: secondary infections per host

# input parameters
R0 <- 1.5   # mean number of secondary infections per host
var.par <- 1   # parameter controlling variation amongst hosts
num.draws <- 10  # number of draws/hosts to draw their number of secondary infections

# randomly draw the number of secondary infections per host
infections <- rnbinom(n=num.draws,size=1/var.par,mu=R0)

# one draw
if(num.draws==1){ print(infections) }

# multiple draws
if(num.draws > 1){
  print(paste("min =",min(infections), sep=" ")); print(paste("max =",max(infections), sep=" ")); print(paste("mean =",mean(infections), sep=" "))
  hist(infections,breaks=seq(from=-0.5,to=max(infections)+0.5,by=1),probability=T,xlab="number of secondary infections",ylab="proportion of cases")
}


#3: outbreak size

# one transmission chain

R0 <- 1.5  
var.par <- 1 

# additional input parameters
max.gens <- 20  # maximum infection generations to simulate
max.N <- 1000   # max number of infected hosts (per gens)

# vectors to store number of infected hosts
num.inf <- numeric(length=max.gens+1)    # number currently infected per gen
cumul.inf <- numeric(length=max.gens+1)  # cumulative number infected
num.inf[1] <- 1
cumul.inf[1] <- 1

# simulation
for(gen in 1:max.gens){  
  
  # random number of secondary infections in previous generation
  new.inf.list <- rnbinom(n=num.inf[gen],size=1/var.par,mu=R0)
  
  # add total # of new in num.inf
  new.inf.tot <- sum(new.inf.list)
  num.inf[gen+1] <- new.inf.tot
  cumul.inf[gen+1] <- cumul.inf[gen] + new.inf.tot
  #num.inf <- c(num.inf,new.inf.tot)
  #cumul.inf <- c(cumul.inf,cumul.inf[gen]+new.inf.tot)
  
  if(new.inf.tot==0){ 
    cumul.inf[(gen+2):(max.gens+1)] <- cumul.inf[gen+1]
    break
  }
  
  if(new.inf.tot > max.N){ 
    num.inf <- num.inf[1:(gen+1)]
    cumul.inf <- cumul.inf[1:(gen+1)]
    break
  }
  
}

#final generation
end.gen <- length(num.inf)-1

# linear scale
plot(0:max.gens,0:max.gens,type="n",ylim=c(0,max(num.inf)+1),xlab="infection generation",ylab="number of infected hosts")
lines(0:end.gen,num.inf,type="s",lwd=4,col='red')
# - log scale
plot(0:max.gens,0.01+0:max.gens,log="y",type="n",ylim=c(0.9,max(num.inf)+1),xlab="infection generation",ylab="number of infected hosts")
lines(0:end.gen,num.inf+0.01,type="s",lwd=4,col='red')

# cumulative number of infected hosts
plot(0:max.gens,0:max.gens,type="n",ylim=c(0,max(cumul.inf)+1),xlab="infection generation",ylab="cumulative number of infected hosts")
lines(0:end.gen,cumul.inf,type="s",lwd=4,col='red')
# - log scale
plot(0:max.gens,0.01+0:max.gens,log="y",type="n",ylim=c(0.9,max(cumul.inf)+1),xlab="infection generation",ylab="cumulative number of infected hosts")
lines(0:end.gen,cumul.inf+0.01,type="s",lwd=4,col='red')


# calculate summary statistics

R0 <- 1.5 
var.par <- 1


max.gens <- 20  
max.N <- 1000
num.sims <- 100

# variables to store outputs
end.gen <- numeric(length=num.sims)       # final simulated generation
num.inf.peak <- numeric(length=num.sims)  # maximum # of infected hosts in any generation
num.inf.end <- numeric(length=num.sims)   # number of infected hosts in the final simulated generation
outbreak.size <- numeric(length=num.sims) # cumulative number of infected hosts

# simulate
for(sim in 1:num.sims){  # loop over simulation runs
  
 
  num.inf <- numeric(length=max.gens+1)    # number currently infected in each generation
  cumul.inf <- numeric(length=max.gens+1)  # cumulative number infected

  num.inf[1] <- 1
  cumul.inf[1] <- 1
  
  for(gen in 1:max.gens){  
   
   
    new.inf.list <- rnbinom(n=num.inf[gen],size=1/var.par,mu=R0)
    

    new.inf.tot <- sum(new.inf.list)
    num.inf[gen+1] <- new.inf.tot
    cumul.inf[gen+1] <- cumul.inf[gen] + new.inf.tot
    
    if(new.inf.tot==0){ 
      cumul.inf[(gen+2):(max.gens+1)] <- cumul.inf[gen+1]
      break
    }
    
    if(new.inf.tot > max.N){  
      num.inf <- num.inf[1:(gen+1)] 
      cumul.inf <- cumul.inf[1:(gen+1)] 
      break  
    }
     
  }  
  

  end.gen[sim] <- gen
  num.inf.peak[sim] <- max(num.inf)
  num.inf.end[sim] <- rev(num.inf)[1]
  outbreak.size[sim] <- rev(cumul.inf)[1]
  
} 

# identify which simulations went extinct and which did not
sims.extinct <- which(num.inf.end==0)
sims.active <- which(num.inf.end > 0)

# analysing the output stats


frac.extinct <- sum(num.inf.end==0)/num.sims
print(paste("fraction extinct: ",frac.extinct,sep=""))


gen.extinct <- end.gen[sims.extinct]
hist(gen.extinct,breaks=seq(from=0.5,to=max(gen.extinct)+0.5,by=1),probability=T)
print(paste("median extinction time: ",median(gen.extinct),"; maximum extinction time: ",max(gen.extinct),sep=""))

# peak number of infected individuals in any generation?

hist(num.inf.peak)
#outbreaks that went extinct:
peak.extinct <- num.inf.peak[sims.extinct]
hist(peak.extinct,breaks=seq(from=0.5,to=max(peak.extinct)+0.5,by=1))
print(paste("peak number infected if outbreak went extinct: median = ",median(peak.extinct),sep=""))
# outbreaks that remained active
peak.active <- num.inf.peak[sims.active]
hist(peak.active)
print(paste("peak number infected if outbreak still active: median = ",median(peak.active),sep=""))

# total cumulative outbreak size
# all simulations together
hist(outbreak.size)
# outbreaks that went extinct:
outbreak.size.extinct <- outbreak.size[sims.extinct]
hist(outbreak.size.extinct,breaks=seq(from=0.5,to=max(outbreak.size.extinct)+0.5,by=1))
print(paste("Outbreak sizes for extinct outbreaks: median = ",median(outbreak.size.extinct),
            "; min = ",min(outbreak.size.extinct), "; max = ",max(outbreak.size.extinct),sep=""))
# outbreaks that remained active
outbreak.size.active <- outbreak.size[sims.active]
hist(outbreak.size.active)
print(paste("Outbreak sizes for active outbreaks: median = ",median(outbreak.size.active),
            "; min = ",min(outbreak.size.active), "; max = ",max(outbreak.size.active),sep=""))

